### PR TITLE
Link to more instructions for Alexa

### PR DESCRIPTION
**Pull request by SLaks**
Use the following YAML, with [lovelace-auto-entities](https://github.com/thomasloven/lovelace-auto-entities), to render a card with a separate bar for every timer in every Alexa device in Alexa Media Player.

This renders identically to #140 (except without dismiss buttons, which Alexa does not support).

```yaml
type: custom:auto-entities
filter:
  template: |
    {%- set results = namespace(timers = []) -%}
    {%- set state_map = {
      "ON": "active",
      "PAUSED": "paused",
    } -%}
    {%- set icon_map = {
      "ON": "mdi:timer",
      "ringing": "mdi:timer-alert",
      "PAUSED": "mdi:timer-pause",
    } -%}
    {%- for entity_id in integration_entities('alexa_media') if entity_id
          is contains 'next_timer' -%}
      {%- set multiple = not loop.first or not loop.last -%}
      {%- set suffix = '' if not multiple
                  else ' – ' + state_attr(entity_id, 'friendly_name')
                      | replace(' timers', '') -%}
            
      {%- for kvp in state_attr(entity_id, 'sorted_all') | from_json if kvp[1].status != "OFF" -%}
        {%- set t= kvp[1] -%}
        {%- set label  = t.timerLabel if t.timerLabel else 
            timedelta(milliseconds = t.originalDurationInMillis) | string | regex_replace('^0:0*', '') + ' timer' -%}   
        {%- set results.timers = results.timers + [{
          'icon': icon_map[t.status],
          'duration': {'fixed': t.originalDurationInMillis | int / 1000, 'units': 'seconds'},
          'end_time': {'fixed': (t.triggerTime | int / 1000) | timestamp_local },
          'name': label + suffix,
          'state': {'fixed': state_map[t.status] | default(t.status)},
        }] -%}
      {%- endfor -%}
    {%- endfor -%}
    {{ results.timers }}
card:
  type: custom:timer-bar-card
show_empty: false
```

### CODE REVIEW

**Comment by rianadon** [comment]
So cool you have this working!

**Comment by s-hutter** [comment]
The template seems to break if one of the devices in 'unavailable'. Pasting the code into the dev tools template editor results in the following error:
`JSONDecodeError: Input must be bytes, bytearray, memoryview, or str: line 1 column 1 (char 0)`

This can be fixed by changing
`{%- for entity_id in integration_entities('alexa_media') if entity_id is contains 'next_timer' -%}`
to only allow entites which are not unavailable:
`{%- for entity_id in integration_entities('alexa_media') if entity_id is contains 'next_timer' and states(entity_id) != 'unavailable' -%}`

**Comment by s-hutter** [comment]
Any chance this could be adapted to use the mushroom style of timer-bar-card instead of the standard "entities" look?

**Comment by phipz** [comment]
> Any chance this could be adapted to use the mushroom style of timer-bar-card instead of the standard "entities" look?

Mushroom Cards only support a single timer. Hence, for each timer a new card need to be created. This works with the following code:

`type: custom:auto-entities
filter:
  template: >
    {%- set results = namespace(timers = []) -%}

    {%- set state_map = {
      "ON": "active",
      "PAUSED": "paused",
    } -%}

    {%- set icon_map = {
      "ON": "mdi:timer",
      "ringing": "mdi:timer-alert",
      "PAUSED": "mdi:timer-pause",
    } -%}

    {%- for entity_id in integration_entities('alexa_media') if entity_id is
    contains 'next_timer' and states(entity_id) != 'unavailable' -%}
      {%- set multiple = not loop.first or not loop.last -%}
      {%- set suffix = '' if not multiple
                  else ' – ' + state_attr(entity_id, 'friendly_name')
                      | replace(' timers', '') -%}
            
      {%- for kvp in state_attr(entity_id, 'sorted_all') | from_json if kvp[1].status != "OFF" -%}
        {%- set t= kvp[1] -%}
        {%- set label  = t.timerLabel if t.timerLabel else 
            timedelta(milliseconds = t.originalDurationInMillis) | string | regex_replace('^0:0*', '') + ' timer' -%}   
        {%- set results.timers = results.timers + [{
          'type': 'custom:timer-bar-card',
          'entity': entity_id,
          'mushroom': true,
          'icon': icon_map[t.status],
          'duration': {'fixed': t.originalDurationInMillis | int / 1000, 'units': 'seconds'},
          'end_time': {'fixed': (t.triggerTime | int / 1000) | timestamp_local },
          'name': label + suffix,
          'state': {'fixed': state_map[t.status] | default(t.status)},
        }] -%}
      {%- endfor -%}
    {%- endfor -%}

    {{ results.timers }}
card:
  type: grid
  columns: 1
  square: false
card_param: cards
show_empty: false
`

image

**Comment by rvroon** [comment]
The mushroom code stopped working for me (after an update of Alexa Media Player), but with this changes I fixed it:
```
type: custom:auto-entities
filter:
  template: >
    {%- set results = namespace(timers = []) -%} 
    {%- set state_map = {
      "ON": "active",
      "PAUSED": "paused",
    } -%} 
    {%- set icon_map = {
      "ON": "mdi:timer",
      "ringing": "mdi:timer-alert",
      "PAUSED": "mdi:timer-pause",
    } -%} 
    {%- for entity_id in integration_entities('alexa_media') if entity_id is contains 'next_timer' and states(entity_id) != 'unavailable' -%}
      {%- set multiple = not loop.first or not loop.last -%}
      {%- set suffix = '' if not multiple
                  else ' – ' + state_attr(entity_id, 'friendly_name')
                      | replace(' next Timer', '') | replace(' Next Timer', '') -%}
            
      {%- set all_timers = state_attr(entity_id, 'sorted_all') -%}
      {%- if all_timers -%}
        {%- for t in all_timers if t.status != "OFF" -%}
          {%- set original_duration_s = t.originalDurationInMillis / 1000 -%}
          {%- set trigger_time_s = t.triggerTime / 1000 -%}
          
          {%- set label = t.timerLabel if t.timerLabel else 
              timedelta(seconds=original_duration_s) | string | regex_replace('^0:0*', '') + ' timer' -%}   
          {%- set results.timers = results.timers + [{
            'type': 'custom:timer-bar-card',
            'entity': entity_id,
            'mushroom': true,
            'icon': icon_map.get(t.status, 'mdi:timer'),
            'duration': {'fixed': original_duration_s, 'units': 'seconds'},
            'end_time': {'fixed': trigger_time_s | timestamp_local },
            'name': label + suffix,
            'state': {'fixed': state_map.get(t.status, t.status | lower)},
          }] -%}
        {%- endfor -%}
      {%- endif -%}
    {%- endfor -%} 
    {{ results.timers }}
card:
  type: grid
  columns: 1
  square: false
card_param: cards
show_empty: false
```

**Pull request merged**
